[package]
name = "aoc-2025-02"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "aoc-2025-02-silver"
path = "src/bin/silver.rs"


[lints]
workspace = true
